name: nordic_nrf_mesh_example
description: Demonstrates how to use the nordic_nrf_mesh plugin.
version: 1.2.0

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^5.2.4
  get: ^4.6.6
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0

  nordic_nrf_mesh:
    path: ../
  flutter_svg: ^2.0.9
  app_settings: ^5.1.1
  flutter_blue_plus: ^1.31.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/mesh.svg
